version: '3.1'
services:
  db:
    container_name: myDataBase
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mydb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: "yelo"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080




